export const PG_MANAGER = "PG_MANAGER";
export const PG_CLIENT = "PG_CLIENT";

// MIDDLEWARE
export const USER_EXCEPTION_FILTER = "USER_EXCEPTION_FILTER";

// REPOSITORIES
export const USER_WRITE_REPOSITORY = "USER_WRITE_REPOSITORY";
export const USER_READ_REPOSITORY = "USER_READ_REPOSITORY";

// COMMANDS
export const COMMAND_DISPATCHER = "COMMAND_DISPATCHER";

// QUERIES
export const QUERY_DISPATCHER = "QUERY_DISPATCHER";
